import tensorflow as tf
import glob
import matplotlib.pyplot as plt
import numpy as np
import os
import PIL
from tensorflow.keras import layers
import time
from IPython import display
from tensorflow.keras.utils import plot_model
from PIL import Image

def make_discriminator_model():
    """
    Returns a discriminator model using Convolutional Neural Network (CNN) architecture.

    Input:
    This function does not take any input.

    Returns:
    model : A tf.keras.Sequential model representing the discriminator

    Input shape of model: (batch_size, 28, 28, 1)
    Output shape of model: (batch_size, 1)
    """
    model = tf.keras.Sequential()
    model.add(layers.Conv2D(64, (5, 5), strides=(2, 2), padding='same',
                                     input_shape=[128, 128, 1]))
    model.add(layers.LeakyReLU())
    model.add(layers.Dropout(0.3))

    model.add(layers.Conv2D(128, (5, 5), strides=(2, 2), padding='same'))
    model.add(layers.LeakyReLU())
    model.add(layers.Dropout(0.3))

    model.add(layers.Flatten())
    model.add(layers.Dense(1))

    return model

def get_decision(decision):
  """
  This function takes in a decision tensor generated by the discriminator and
  prints whether the image is real or generated by the AI. If the decision value
  is less than 0, the image is considered to be generated by the AI, and
  if it is greater than or equal to 0, the image is considered to be real.

  Input:
  decision: Tensor of shape (1, 1) containing the decision value for an image generated by the discriminator

  Returns:
  None
  """

  val = decision.numpy()[0, 0]
  if val < 0:
    print("AI generated image")
  else:
    print("real image")

if __name__ == '__main__':

    imgPath = "../allImages/train/noised/gaussian/banana1.jpg"
    
    generated_image = Image.open(imgPath).convert('L') 
    generated_image = generated_image.resize((128, 128))

    img_array = np.array(generated_image, dtype=np.float32)
    img_array = img_array / 255.0

    img_array = np.expand_dims(img_array, axis=-1)  
    img_array = np.expand_dims(img_array, axis=0)  

    discriminator = make_discriminator_model()

    decision = discriminator(img_array)

    get_decision(decision)
    print("ok")